def mostrar_ayuda():
    """Genera las ayudas del sistema"""

    yield "********** COMANDOS DISPONIBLES **********"
    yield ""
    yield "CONSULTAS:"
    yield "     S P O ?                     - Consulta si existe el hecho o busca valores para variables"
    yield ""
    yield "AGREGAR HECHOS:"
    yield "     S P O .                     - Agregar un nuevo hecho a la base de conocimientos"
    yield "     S P O . [confianza]         - Agregar un nuevo hecho a la base de conocimientos con factor de confianza [0.0, 1.0]"
    yield ""
    yield "REVOCAR HECHOS:"
    yield "     no S P O .                  - Eliminar un hecho de la base de conocimientos"
    yield ""
    yield "RAZONAR: "
    yield "     razona si S P O ?           - Razonaminento sobre la base de conocimientos"
    yield ""
    yield "DESCUBRIR: "
    yield "     descubrir!                  - Descubre nuevos hechos"
    yield ""
    yield "SALIR: "
    yield "     exit, quit, q, cerrar, e    - Salir del programa"
    yield ""
    yield "AYUDA:"
    yield "     help, h, ayuda              - Mostrar panel de ayuda"
    yield ""
